version: 2.1

commands:
  all-tests:
    description: "Roda todos os testes do projeto (unitários e integração)"
    steps:
      - run: "pipenv run test"

  typehint-coverage:
    description: "Upload de coverage de typehint"
    steps:
      - run:
          name: "Typehint coverage report"
          command: |
            mkdir -p .mypy/xml/cov
            pipenv run lint --cobertura-xml-report .mypy/xml/cov
            pipenv run codecov --flags typehint --file .mypy/xml/cov/cobertura.xml
            rm -rf .mypy/


  test-coverage:
    description: "Upload unittest coverage data"
    steps:
      - run: "pipenv run codecov --flags unittest"

jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install pip/pipenv
          command: pip install --user -U pip==19.3.1 pipenv==2018.11.26
      - run:
          name: Install Pipfile.lock
          command: pipenv install --deploy --ignore-pipfile --dev
      - run:
          name: Install project in dev-mode
          command: pipenv run pip install -e .
      - typehint-coverage
      - all-tests
      - test-coverage
workflows:
  version: 2
  test:
    jobs:
      - test
